name: tictac_riverpod
description: A beautiful Tic Tac Toe game with Riverpod and Clean Architecture
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Code Generation
  freezed_annotation: ^2.4.1

  # UI
  google_fonts: ^6.1.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.5.7

flutter:
  uses-material-design: true